version: 2.1
orbs:
  node: circleci/node@4.7.0
  docker: circleci/docker@2.0.1
  slack: circleci/slack@4.5.0

jobs:

  build-base:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - run:
          name: Clean up artifacts
          command: |
            cd base && rm -rf ./node_modules
      - docker/build:
          docker-context: base
          image: thinxcloud/base
          dockerfile: ./base/Dockerfile
          extra_build_args: |
            --build-arg REVISION=$(git describe --abbrev=0) \
          tag: 'latest'
      - docker/push:
          digest-path: /tmp/digest.txt
          image: thinxcloud/base
          tag: 'latest'

  build-console-cloud:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Fetch all dependencies (esp. console)
          command: |
            git submodule foreach --recursive 'git submodule sync' && git submodule update --init --recursive
      - docker/check:
          registry: registry.thinx.cloud:5000
      - docker/build:
          registry: registry.thinx.cloud:5000
          docker-context: services/console/src
          image: thinx/console
          dockerfile: services/console/src/Dockerfile
          extra_build_args: |
            --build-arg ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN} \
            --build-arg LANDING_HOSTNAME=${LANDING_HOSTNAME} \
            --build-arg API_HOSTNAME=${API_HOSTNAME} \
            --build-arg API_BASEURL=${API_BASEURL} \
            --build-arg WEB_HOSTNAME=${WEB_HOSTNAME} \
            --build-arg GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID} \
            --build-arg CRISP_WEBSITE_ID=${CRISP_WEBSITE_ID} \
            --build-arg ENTERPRISE=true \
            --build-arg ENVIRONMENT=${ENVIRONMENT} \
          tag: 'swarm'
      - docker/push:
          digest-path: /tmp/digest.txt
          image: thinx/console
          registry: registry.thinx.cloud:5000
          tag: 'swarm'

  build-api-cloud:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: thinxcloud/api
          dockerfile: ./Dockerfile
          extra_build_args: |
            --build-arg AQUA_SEC_TOKEN=${AQUA_SEC_TOKEN} \
            --build-arg SNYK_TOKEN=${SNYK_TOKEN} \
            --build-arg ENVIRONMENT=${ENVIRONMENT} \
            --build-arg REVISION=$(git describe --abbrev=0) \
          tag: 'latest'
      - docker/push:
          digest-path: /tmp/digest.txt
          image: thinxcloud/api
          tag: 'latest'

  test-api-cloud:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          registry: registry.thinx.cloud:5000
      - docker/build:
          registry: registry.thinx.cloud:5000
          image: thinx/api
          dockerfile: ./Dockerfile.test
          extra_build_args: |
            --build-arg AQUA_SEC_TOKEN=${AQUA_SEC_TOKEN} \
            --build-arg SNYK_TOKEN=${SNYK_TOKEN} \
            --build-arg ENVIRONMENT=${ENVIRONMENT} \
            --build-arg REVISION=$(git describe --abbrev=0) \
          tag: 'swarm'
  
  test:

    docker:
      - image: thinxcloud/base:latest
        auth:
          username: $DOCKER_USERNAME  # from thinx-docker-repo, docker.io
          password: $DOCKER_PUBLIC_PASSWORD  # or project environment variable reference

    working_directory: ~/suculent/thinx-device-api

    parallelism: 1

    shell: /bin/bash --login

    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      REDIS_URL: redis://localhost:6379

    steps:

    - run:
        name: Install Docker Compose
        environment:
          COMPOSE_VERSION: '1.29.2'
        command: |
          curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
          chmod +x ~/docker-compose
          mv ~/docker-compose /usr/local/bin/docker-compose

    - setup_remote_docker

    - checkout

    # Restore the dependency cache
    - restore_cache:
        keys:
          # This branch if available
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - run:
        name: Fetch all submodules and tests
        command: |
          git submodule foreach --recursive 'git submodule sync' && git submodule update --init --recursive
          cd spec/test_repositories && bash ./get-tests.sh

    - run:
        name: Create Circle CI Artifacts Folders
        command: |
          mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
          mkdir -p $CIRCLE_TEST_REPORTS/reports

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: Init filesystem
        command: |
            mkdir -p /mnt/data/
            mkdir -p /mnt/data && cp -R ./conf /mnt/data
            mkdir -p /mnt/data/ssh_keys
            mkdir -p /mnt/data/mosquitto/auth
            mkdir -p /mnt/data/mosquitto/config
            mkdir -p /mnt/data/mosquitto/data
            mkdir -p /mnt/data/mosquitto/log
            mkdir -p /mnt/data/mosquitto/ssl
            mkdir -p /mnt/data/couchdb
            mkdir -p /mnt/data/deploy
            mkdir -p /mnt/data/data
            mkdir -p /mnt/data/redis
            mkdir -p /mnt/data/repos
            mkdir -p /mnt/data/ssl
            mkdir -p /mnt/data/test-reports

    - run:
        name: Switch to Test Dockerfiles
        command: |
          rm -rf ./Dockerfile
          mv ./Dockerfile.test ./Dockerfile
          rm -rf ./docker-compose.yml
          mv ./docker-compose.test.yml ./docker-compose.yml
          rm -rf ./services/broker/Dockerfile
          mv ./services/broker/Dockerfile.test ./services/broker/Dockerfile
          sed -i "s/.git//g" .dockerignore
          echo "Creating Docker Network (ID):"
          docker network create nat

    - run:
        name: Copy Environment variables for in-place building
        command: |
          cp -vf ./.env.dist ./.env
          cp -vf ./.env.dist ./spec/mnt/data/conf/.env
          cp -vf ./.env ./services/broker/.env
          cp -vf ./.env ./services/console/.env
          cp -vf ./.env ./services/couchdb/.env
          cp -vf ./.env ./services/redis/.env
          cp -vf ./.env ./services/transformer/.env

    - run:
        name: Review configuration and environment
        command: |
          echo "Contents of ./conf"
          ls -la ./conf
          echo "Contents of ./.env"
          cat ./.env

    - run:
        name: Inject password to configuration and broker
        command: |
          echo "Injecting secret: ${REDIS_PASSWORD}"
          sed -i "s/changeme!/${REDIS_PASSWORD}/g" ./services/broker/test/mosquitto/mosquitto.conf
          sed -i "s/changeme!/${REDIS_PASSWORD}/g" ./spec/mnt/data/conf/config.json
          cp ./spec/mnt/data/conf/config.json /mnt/data/conf/config.json

    - run:
        name: Starting Redis
        command: |
          docker-compose up -d --build thinx-redis
          docker-compose logs --timestamp thinx-redis

    - run:
        name: Starting Mosquitto
        command: |
          docker login --username $DOCKER_LOGIN --password $DOCKER_PASSWORD https://registry.thinx.cloud:5000
          docker-compose up -d --build mosquitto
          docker-compose logs --timestamp mosquitto

    - run:
        name: Starting Transformer
        command: |
          docker-compose up -d --build transformer
          docker-compose logs --timestamp transformer

    - run:
        name: Starting CouchDB
        command: |
          export ENVIRONMENT=test
          chmod -R 666 ./services/couchdb/*
          docker-compose up -d --build couchdb
          docker-compose logs --timestamp couchdb

    - run:
        name: Starting API Test
        command: |
          export ENVIRONMENT=test
          docker-compose up --build api
          echo "###### > Tailing completed, stopping job."
          date

    - run:
        name: Allow inspecting MQTT logs after failed connections
        command: |
            docker-compose logs --timestamp mosquitto

    - run:
        name: Allow inspecting CouchDB logs after failed connections
        command: |
            docker-compose logs --timestamp couchdb

    - run:
        name: Allow inspecting Transformer logs after failed connections
        command: |
            docker-compose logs --timestamp transformer

    - run:
        name: Check running Docker containers
        command: |
            docker ps
            docker network ls
            docker network inspect bridge
            docker-compose stop

    - store_test_results:
        name: Collect test results
        path: ./coverage
        # The `path` key is an absolute or relative path to your working_directory containing 
        # subdirectories of JUnit XML or Cucumber JSON test metadata files,
        # or the path of a single file containing all test results.
        # Make sure that your path value is not a hidden folder (example: .my_hidden_directory would be an invalid format).

    - store_artifacts:
        name: Collect coverage data
        path: ./coverage
        destination: jest-coverage

#
# WORKFLOWS
#

workflows:

  #
  # public open-source site
  #

  build-and-deploy:

    jobs:

      - test:
          context:
              - dockerhub
              - thinx-docker-repo
              - thinx-test
              - sonarcloud
          #requires:
          #  - build-base
          filters:
            branches:
              only:
                - base
                - thinx-swarm
                - main
                - thinxcloud

      # - test-api-cloud:
      #     context:
      #         - thinx-docker-repo
      #     filters:
      #       branches:
      #         only:
      #           - thinx-swarm
      
      - build-console-cloud:
          context:
            - thinx-docker-repo
            - console
          filters:
            branches:
              only:
                - thinx-swarm

      - build-base:
          context:
            - dockerhub
          filters:
            branches:
              only:
                - base
                #- thinxcloud
                #- thinx-swarm

      - build-api-cloud:
          context:
            - dockerhub
            - SonarCloud
          requires:
            #- test-api-cloud
            - test
          filters:
            branches:
              only:
                - thinx-swarm
                - thinxcloud