version: 2.1

orbs: 
  docker: circleci/docker@2.5.0
  ggshield: gitguardian/ggshield@1.1.4

workflows:
  build-and-publish:
    jobs:
      - docker/publish:
          name: Build and Publish to Docker Hub
          image: thinxcloud/mosquitto
          tag: latest
          context:
            - dockerhub